name = "practice-cloudflare-workers-rust"
main = "build/worker/shim.mjs"
compatibility_date = "2025-03-16"

[build]
command = "curl https://sh.rustup.rs -sSf | sh; cargo install -q worker-build && worker-build --release"
